import { useState } from 'react'
import { AlertTriangle, CheckCircle2, Database, KeyRound, LockKeyhole, Server, Store, UserRound } from 'lucide-react'

const Status = ({ ready, children }) => <span className={ready ? 'badge-green' : 'badge-yellow'}>{children}</span>
const Value = ({ children, pending = false }) => <dd className={pending ? 'font-semibold text-amber-700' : 'font-medium text-gray-900'}>{children || 'PENDING_CONFIRMATION'}</dd>

export default function FiscalConfigurationPanel({ config, readiness }) {
  const [sequence, setSequence] = useState({ last: '', next: '', source: '', date: '', responsible: '', confirm1: false, confirm2: false })
  const [message, setMessage] = useState('')
  const issuer = config?.issuer || {}
  const checks = readiness?.checks || []
  const simulateSequence = (event) => {
    event.preventDefault(); setMessage('')
    if (Number(sequence.next) !== Number(sequence.last) + 1 || !sequence.source || !sequence.date || !sequence.responsible || !sequence.confirm1 || !sequence.confirm2) return setMessage('Completa la fuente, responsable, fecha, continuidad y doble confirmación.')
    setMessage('Simulación local validada. No cambió ningún secuencial oficial ni productivo.')
  }
  return <div className="space-y-4">
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="card"><h2 className="flex items-center gap-2 font-semibold text-brand-900"><UserRound size={18} /> Perfil del emisor</h2><dl className="mt-4 grid grid-cols-[140px_1fr] gap-x-3 gap-y-3 text-sm"><dt className="text-gray-500">RUC</dt><Value>{issuer.rucPlaceholder}</Value><dt className="text-gray-500">Razón social</dt><Value>{issuer.businessName}</Value><dt className="text-gray-500">Nombre comercial</dt><Value>{issuer.tradeName}</Value><dt className="text-gray-500">Matriz</dt><Value pending={issuer.headOfficeAddress === 'PENDING_CONFIRMATION'}>{issuer.headOfficeAddress}</Value><dt className="text-gray-500">Ciudad</dt><Value>{issuer.city}</Value><dt className="text-gray-500">Teléfono</dt><Value>{issuer.phone}</Value><dt className="text-gray-500">Correo</dt><Value>{issuer.email}</Value><dt className="text-gray-500">Contabilidad</dt><Value pending={!issuer.accountingObligationConfirmed}>{issuer.accountingObligationConfirmed ? issuer.accountingObligation : 'PENDING_CONFIRMATION'}</Value><dt className="text-gray-500">Régimen</dt><Value pending={issuer.regimeInformation === 'PENDING_CONFIRMATION'}>{issuer.regimeInformation}</Value></dl></section>
      <section className="card"><h2 className="flex items-center gap-2 font-semibold text-brand-900"><Store size={18} /> Establecimientos y puntos</h2><div className="mt-4 space-y-3 text-sm"><div className="rounded-xl border p-3"><div className="flex items-center justify-between"><strong>Establecimiento {config?.establishment?.code}</strong><Status ready={config?.establishment?.status === 'READY'}>{config?.establishment?.status === 'READY' ? 'Confirmado' : 'Parcial'}</Status></div><p className="mt-2 text-gray-500">{config?.establishment?.address}</p></div><div className="rounded-xl border p-3"><div className="flex items-center justify-between"><strong>Punto {config?.emissionPoint?.code}</strong><Status ready={config?.emissionPoint?.status === 'READY'}>{config?.emissionPoint?.status === 'READY' ? 'Confirmado' : 'Bloqueado'}</Status></div><p className="mt-2 text-gray-500">Secuencial inicial: {config?.emissionPoint?.sequenceStart}</p></div></div></section>
      <section className="card"><h2 className="flex items-center gap-2 font-semibold text-brand-900"><KeyRound size={18} /> Firma electrónica</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-gray-500">Estado</p><p className="font-semibold text-amber-700">{config?.certificate?.configured ? 'Configurada localmente' : 'No configurada'}</p></div><div><p className="text-gray-500">Tipo esperado</p><p className="font-medium">.p12 o .pfx</p></div><div><p className="text-gray-500">Alias lógico</p><p className="font-medium">{config?.certificate?.alias}</p></div><div><p className="text-gray-500">Contraseña</p><p className="font-medium">{config?.certificate?.passwordConfigured ? 'Secreto configurado' : 'No configurada'}</p></div></div><div className="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-gray-600"><p className="flex items-center gap-2 font-semibold"><LockKeyhole size={15} /> Seguridad</p><p className="mt-1">La ruta completa, la llave y la contraseña nunca se muestran ni se guardan en Git.</p></div></section>
      <section className="card"><h2 className="flex items-center gap-2 font-semibold text-brand-900"><Server size={18} /> Conexión y persistencia</h2><dl className="mt-4 grid grid-cols-[150px_1fr] gap-3 text-sm"><dt className="text-gray-500">Ambiente elegido</dt><Value>{config?.sri?.environment}</Value><dt className="text-gray-500">Conexión oficial</dt><Value><span className="text-red-700">DESHABILITADA</span></Value><dt className="text-gray-500">Almacenamiento</dt><Value>{config?.storage}</Value><dt className="text-gray-500">Persistente</dt><Value>{config?.persistent ? 'Sí' : 'No; se pierde al reiniciar'}</Value><dt className="text-gray-500">XSD</dt><Value>{config?.xsd}</Value><dt className="text-gray-500">Firmador</dt><Value>{config?.signer}</Value></dl></section>
    </div>

    <section className="card"><h2 className="flex items-center gap-2 font-semibold text-brand-900"><Database size={18} /> Configurar secuencial inicial - simulación local</h2><p className="mt-1 text-xs text-gray-500">No activa ni modifica numeración oficial. En modo real exigirá PostgreSQL y auditoría transaccional.</p><form className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4" onSubmit={simulateSequence}><label><span className="label">Último secuencial usado</span><input className="input" type="number" min="0" value={sequence.last} onChange={(event) => setSequence((value) => ({ ...value, last: event.target.value }))} /></label><label><span className="label">Próximo secuencial</span><input className="input" type="number" min="1" value={sequence.next} onChange={(event) => setSequence((value) => ({ ...value, next: event.target.value }))} /></label><label><span className="label">Fuente de verificación</span><input className="input" value={sequence.source} onChange={(event) => setSequence((value) => ({ ...value, source: event.target.value }))} /></label><label><span className="label">Fecha</span><input className="input" type="date" value={sequence.date} onChange={(event) => setSequence((value) => ({ ...value, date: event.target.value }))} /></label><label className="lg:col-span-2"><span className="label">Responsable</span><input className="input" value={sequence.responsible} onChange={(event) => setSequence((value) => ({ ...value, responsible: event.target.value }))} /></label><div className="space-y-2 text-xs"><label className="flex gap-2"><input type="checkbox" checked={sequence.confirm1} onChange={(event) => setSequence((value) => ({ ...value, confirm1: event.target.checked }))} /> Confirmo que revisé la fuente.</label><label className="flex gap-2"><input type="checkbox" checked={sequence.confirm2} onChange={(event) => setSequence((value) => ({ ...value, confirm2: event.target.checked }))} /> Confirmo que no es un dato simulado.</label></div><button className="btn-secondary self-end justify-center">Validar simulación</button></form>{message && <p className={`mt-3 text-sm ${message.startsWith('Simulación') ? 'text-emerald-700' : 'text-red-700'}`}>{message}</p>}</section>

    <section className="card"><h2 className="font-semibold text-brand-900">Checklist de preparación</h2><div className="mt-4 grid gap-2 md:grid-cols-2">{checks.map((check) => <article key={check.key} className="flex items-start gap-3 rounded-xl border border-gray-200 p-3">{check.status === 'READY' ? <CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600" size={18} /> : <AlertTriangle className="mt-0.5 shrink-0 text-amber-600" size={18} />}<div><p className="text-sm font-semibold">{check.label}</p><p className="mt-1 text-xs text-gray-500">{check.detail}</p><p className="mt-1 text-[10px] font-bold text-gray-400">{check.status}</p></div></article>)}</div></section>
  </div>
}
