import { useState } from 'react'
import { AlertTriangle, CheckCircle2, Database, HardDrive, Info, KeyRound, LockKeyhole, Server, Store, UserRound } from 'lucide-react'

const humanValue = (value) => !value || value === 'PENDING_CONFIRMATION' ? 'Pendiente de confirmación' : value
const Status = ({ ready, children }) => <span className={ready ? 'badge-green' : 'badge-yellow'}>{children}</span>
const Value = ({ children, pending = false }) => <dd className={pending || children === 'PENDING_CONFIRMATION' ? 'font-semibold text-amber-700' : 'font-medium text-gray-900'}>{humanValue(children)}</dd>
const statusLabel = (status) => ({ READY: 'Listo', PARTIAL: 'Parcial', BLOCKED: 'Bloqueado', REQUIRES_CONFIRMATION: 'Requiere confirmación', REQUIRES_CERTIFICATE: 'Requiere certificado', REQUIRES_CERTIFICATION: 'Requiere certificación' }[status] || status)

const groups = [
  { key: 'CERTIFICATION_REQUIRED', title: 'A. Obligatorio para certificación', description: 'Información y pruebas necesarias antes de iniciar la certificación con el SRI.' },
  { key: 'PRODUCTION_REQUIRED', title: 'B. Obligatorio antes de producción', description: 'Controles operativos y de seguridad que deben resolverse antes de emitir oficialmente.' },
  { key: 'RECOMMENDED_INFRASTRUCTURE', title: 'C. Infraestructura recomendada', description: 'Mejoras técnicas recomendadas; no son requisitos legales ni tributarios.' },
]

export default function FiscalConfigurationPanel({ config, readiness }) {
  const [sequence, setSequence] = useState({ last: '', next: '', source: '', date: '', responsible: '', confirm1: false, confirm2: false })
  const [message, setMessage] = useState('')
  const issuer = config?.issuer || {}
  const checks = readiness?.checks || []
  const sequencePending = config?.emissionPoint?.sequenceStart === 'PENDING_CONFIRMATION'

  const simulateSequence = (event) => {
    event.preventDefault(); setMessage('')
    if (Number(sequence.next) !== Number(sequence.last) + 1 || !sequence.source || !sequence.date || !sequence.responsible || !sequence.confirm1 || !sequence.confirm2) return setMessage('Completa la fuente, responsable, fecha, continuidad y doble confirmación.')
    setMessage('Validación de prueba completada. No se guardó ni modificó ningún secuencial oficial.')
  }

  return <div className="space-y-4">
    <div><h2 className="text-lg font-semibold">Configuración fiscal</h2><p className="text-sm text-gray-500">Datos institucionales, conexión, persistencia y preparación del módulo.</p></div>

    <div className="grid gap-4 xl:grid-cols-2">
      <section className="card"><h3 className="flex items-center gap-2 font-semibold text-brand-900"><UserRound size={18} /> Perfil del emisor</h3><dl className="mt-4 grid grid-cols-[120px_minmax(0,1fr)] gap-x-3 gap-y-3 break-words text-sm sm:grid-cols-[150px_minmax(0,1fr)]"><dt className="text-gray-500">RUC</dt><Value>{issuer.rucPlaceholder}</Value><dt className="text-gray-500">Razón social</dt><Value>{issuer.businessName}</Value><dt className="text-gray-500">Nombre comercial</dt><Value>{issuer.tradeName}</Value><dt className="text-gray-500">Matriz</dt><Value pending={issuer.headOfficeAddress === 'PENDING_CONFIRMATION'}>{issuer.headOfficeAddress}</Value><dt className="text-gray-500">Ciudad</dt><Value>{issuer.city}</Value><dt className="text-gray-500">Teléfono</dt><Value>{issuer.phone}</Value><dt className="text-gray-500">Correo</dt><Value>{issuer.email}</Value><dt className="text-gray-500">Contabilidad</dt><Value pending={!issuer.accountingObligationConfirmed}>{issuer.accountingObligationConfirmed ? issuer.accountingObligation : 'PENDING_CONFIRMATION'}</Value><dt className="text-gray-500">Régimen</dt><Value pending={issuer.regimeInformation === 'PENDING_CONFIRMATION'}>{issuer.regimeInformation}</Value></dl></section>

      <section className="card"><h3 className="flex items-center gap-2 font-semibold text-brand-900"><Store size={18} /> Establecimientos y puntos</h3><div className="mt-4 space-y-3 text-sm"><div className="rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>Establecimiento {config?.establishment?.code}</strong><Status ready={config?.establishment?.status === 'READY'}>{config?.establishment?.status === 'READY' ? 'Confirmado' : 'Requiere confirmación'}</Status></div><p className="mt-2 break-words text-gray-500">{humanValue(config?.establishment?.address)}</p></div><div className="rounded-xl border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>Punto de emisión {config?.emissionPoint?.code}</strong><Status ready={config?.emissionPoint?.status === 'READY'}>{config?.emissionPoint?.status === 'READY' ? 'Confirmado' : 'Requiere confirmación'}</Status></div><p className="mt-2 text-gray-500">Secuencial inicial: {humanValue(config?.emissionPoint?.sequenceStart)}</p></div></div></section>

      <section className="card"><h3 className="flex items-center gap-2 font-semibold text-brand-900"><KeyRound size={18} /> Firma electrónica</h3><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-gray-500">Modo actual</p><p className="font-semibold text-amber-700">{config?.signer || 'Firma de demostración'}</p></div><div><p className="text-gray-500">Certificado institucional</p><p className="font-medium">{config?.certificate?.configured ? 'Configurado para pruebas' : 'No configurado'}</p></div><div><p className="text-gray-500">Tipo esperado</p><p className="font-medium">.p12 o .pfx</p></div><div><p className="text-gray-500">Contraseña</p><p className="font-medium">{config?.certificate?.passwordConfigured ? 'Secreto configurado' : 'No configurada'}</p></div></div><div className="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-gray-600"><p className="flex items-center gap-2 font-semibold"><LockKeyhole size={15} /> Seguridad</p><p className="mt-1">La ruta completa, la llave y la contraseña nunca se muestran ni se guardan en Git.</p></div></section>

      <section className="card"><h3 className="flex items-center gap-2 font-semibold text-brand-900"><Server size={18} /> Conexión SRI</h3><dl className="mt-4 grid grid-cols-[140px_minmax(0,1fr)] gap-3 text-sm"><dt className="text-gray-500">Ambiente elegido</dt><Value>{config?.sri?.environment === 'CERTIFICATION' ? 'Certificación' : config?.sri?.environment}</Value><dt className="text-gray-500">Conexión oficial</dt><dd className="font-semibold text-red-700">Deshabilitada</dd><dt className="text-gray-500">Validación XSD</dt><Value>{config?.xsd}</Value></dl><p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">No se realizan llamadas reales al SRI desde esta versión.</p></section>

      <section className="card xl:col-span-2"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 font-semibold text-brand-900"><HardDrive size={18} /> Persistencia fiscal segura</h3><p className="mt-1 text-xs text-gray-500">La decisión institucional está pendiente.</p></div><span className="badge-yellow">REQUIRES_CONFIRMATION</span></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl border p-3"><p className="text-xs text-gray-500">Estado actual</p><p className="mt-1 font-semibold">Memoria temporal</p></div><div className="rounded-xl border p-3"><p className="text-xs text-gray-500">Adaptador preparado</p><p className="mt-1 font-semibold">PostgreSQL</p></div><div className="rounded-xl border p-3"><p className="text-xs text-gray-500">Alternativa institucional</p><p className="mt-1 font-semibold text-amber-700">Por definir</p></div><div className="rounded-xl border p-3"><p className="text-xs text-gray-500">Garantías requeridas</p><p className="mt-1 font-semibold">Secuencias, auditoría, idempotencia y respaldos</p></div></div><p className="mt-3 text-xs text-gray-500">PostgreSQL es la opción técnica recomendada para integridad y concurrencia; los adaptadores permiten evaluar alternativas institucionales equivalentes.</p></section>
    </div>

    <details className="card" open>
      <summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 font-semibold text-brand-900"><Database size={18} /> Numeración de comprobantes</h3><p className="mt-1 text-xs text-gray-500">Configuración avanzada</p></div><Status ready={!sequencePending}>{sequencePending ? 'Solo validación de prueba' : 'Dato configurado'}</Status></summary>
      <p className="mt-4 text-sm text-gray-600">Permite registrar el último número utilizado y definir el próximo comprobante, evitando duplicados entre el Facturador SRI y R.A. Training Finance.</p>
      {sequencePending && <div className="mt-3 flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><AlertTriangle size={16} className="mt-0.5 shrink-0" /> El secuencial institucional está pendiente de confirmación. Este formulario únicamente valida datos ficticios y no habilita numeración oficial.</div>}
      <form className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4" onSubmit={simulateSequence}>
        <label><span className="label">Establecimiento</span><input className="input bg-gray-50" value={config?.establishment?.code || '001'} readOnly /></label>
        <label><span className="label">Punto de emisión</span><input className="input bg-gray-50" value={config?.emissionPoint?.code || '001'} readOnly /></label>
        <label><span className="label">Último secuencial usado</span><input className="input" type="number" min="0" inputMode="numeric" value={sequence.last} onChange={(event) => setSequence((value) => ({ ...value, last: event.target.value }))} /></label>
        <label><span className="label">Próximo secuencial</span><input className="input" type="number" min="1" inputMode="numeric" value={sequence.next} onChange={(event) => setSequence((value) => ({ ...value, next: event.target.value }))} /></label>
        <label className="sm:col-span-2"><span className="label inline-flex items-center gap-1">Fuente de verificación <button type="button" className="text-brand-700" title="El último secuencial debe verificarse en el Facturador SRI o en el XML autorizado más reciente." aria-label="Ayuda sobre la fuente de verificación"><Info size={15} /></button></span><input className="input" placeholder="Fuente ficticia para esta validación" value={sequence.source} onChange={(event) => setSequence((value) => ({ ...value, source: event.target.value }))} /></label>
        <label><span className="label">Fecha de verificación</span><input className="input" type="date" value={sequence.date} onChange={(event) => setSequence((value) => ({ ...value, date: event.target.value }))} /></label>
        <label><span className="label">Responsable</span><input className="input" placeholder="Responsable de prueba" value={sequence.responsible} onChange={(event) => setSequence((value) => ({ ...value, responsible: event.target.value }))} /></label>
        <div className="space-y-3 text-xs sm:col-span-2 lg:col-span-3"><label className="flex gap-2"><input type="checkbox" checked={sequence.confirm1} onChange={(event) => setSequence((value) => ({ ...value, confirm1: event.target.checked }))} /> Confirmo que revisé la fuente indicada para esta prueba.</label><label className="flex gap-2"><input type="checkbox" checked={sequence.confirm2} onChange={(event) => setSequence((value) => ({ ...value, confirm2: event.target.checked }))} /> Confirmo que esta validación no guarda ni activa un secuencial oficial.</label></div>
        <button className="btn-secondary self-end justify-center">Validar datos de prueba</button>
      </form>
      {message && <p role="status" className={`mt-3 text-sm ${message.startsWith('Validación') ? 'text-emerald-700' : 'text-red-700'}`}>{message}</p>}
    </details>

    <section className="card"><h3 className="font-semibold text-brand-900">Checklist de preparación</h3><div className="mt-4 space-y-5">{groups.map((group) => { const groupChecks = checks.filter((check) => check.group === group.key); return <div key={group.key}><div><h4 className="text-sm font-semibold text-gray-900">{group.title}</h4><p className="mt-1 text-xs text-gray-500">{group.description}</p></div><div className="mt-3 grid gap-2 md:grid-cols-2">{groupChecks.map((check) => <article key={check.key} className="flex items-start gap-3 rounded-xl border border-gray-200 p-3">{check.status === 'READY' ? <CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600" size={18} /> : <AlertTriangle className="mt-0.5 shrink-0 text-amber-600" size={18} />}<div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{check.label}</p><span className={check.status === 'READY' ? 'badge-green' : 'badge-yellow'}>{statusLabel(check.status)}</span></div><p className="mt-1 text-xs text-gray-500">{check.detail}</p></div></article>)}</div></div> })}</div></section>

    <details className="card text-sm"><summary className="cursor-pointer font-semibold text-brand-900">Información técnica</summary><dl className="mt-4 grid grid-cols-[140px_minmax(0,1fr)] gap-3"><dt className="text-gray-500">Almacenamiento</dt><Value>{config?.storage}</Value><dt className="text-gray-500">Persistente</dt><Value>{config?.persistent ? 'Sí' : 'No; se pierde al reiniciar'}</Value><dt className="text-gray-500">Firmador interno</dt><Value>{config?.signerTechnical || 'mock'}</Value><dt className="text-gray-500">Alias lógico</dt><Value>{config?.certificate?.alias}</Value></dl></details>
  </div>
}
